name: precommit test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Decrypt profile.properties
        run: .github/scripts/decrypt_profile.sh
        env:
          PROFILE_PASSWORD: ${{ secrets.PROFILE_PASSWORD }}
      - name: Run test
        run: mvn install -Dgpg.skip && mvn integration-test -Dgpg.skip -P run-its